apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cs81r4zrc-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cs81r4zrc-dotnet-basic-gitops